---
dependencies:
  - role: dresden-weekly.network-interfaces
    network_manage_devices: no
    network_restart_method: interface

  - role: debops.dhcpd
    dhcpd_authoritative: True
    dhcpd_interfaces: [ "{{ routing.internal_interface }}" ]
    dhcpd_lease_time: 2400
    dhcpd_nameservers: ["8.8.8.8", "8.8.4.4"]

  - role: geerlingguy.firewall
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "443"
      - "8080"
      - "8081"
    firewall_additional_rules:
      - "iptables -A FORWARD -i {{ routing.internal_interface }} -j ACCEPT"
      - "iptables -t nat -A POSTROUTING -o {{ routing.internet_interface }} -j MASQUERADE"
      - "iptables -A FORWARD -i {{ routing.internet_interface }} -o {{ routing.internal_interface }} -m state --state RELATED,ESTABLISHED -j ACCEPT"
      - "iptables -A FORWARD -i {{ routing.internal_interface }} -o {{ routing.internet_interface }} -j ACCEPT"
