---
- name: Install all the necessary packages for routing
  apt:
    name: "{{ item }}"
  with_items:
    - iptables
    - miniupnpd

- name: enable service
  systemd:
    name: miniupnpd
    state: started
    enabled: yes

- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes

- name: configure interfaces
  include_role:
    name: dresden-weekly.network-interfaces
  vars:
    network_manage_devices: no
    network_restart_method: interface
  become: yes

- name: install dhcpd
  include_role:
    name: debops.dhcpd
  vars:
    dhcpd_authoritative: True
    dhcpd_interfaces: [ "{{ routing.internal_interface }}" ]
    dhcpd_lease_time: 2400
    dhcpd_nameservers: ["8.8.8.8", "8.8.4.4"]
